swagger: '2.0'
info:
  title: Identify API
  description: Get an ONID username of a person.
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/identify-api
basePath: /v1
produces:
  - application/json
paths:
  /identify:
    get:
      tags:
        - identify
      description: "Get ONID username of a person selected by query parameters."
      operationId: getONID
      parameters:
        - in: query
          name: osuID
          required: false
          description: "9 digit OSU ID"
          type: string
        - in: query
          name: facilityCode
          required: false
          description: "3 character ID card facility code. Must be used wiith cardID parameter."
          type: string
        - in: query
          name: cardID
          required: false
          description: "ID card code. Must be used wiith facilityCode parameter."
          type: string
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObject'
        "400":
          description: "Bad request. Query parameter is required."
          schema:
            $ref: '#/definitions/Error'
  /identify/{osuuid}:
    get:
      tags:
        - identify
      description: "Get ONID username of a person selected by a query parameter."
      operationId: getONIDbyOSUUID
      parameters:
        - in: path
          name: osuuid
          required: true
          description: "OSUUID of a person."
          type: string
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObject'
        "404":
          description: "Resource not found"
          schema:
            $ref: "#/definitions/Error"
            
parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObject:
    properties:
      data:
        $ref: "#/definitions/ResourceObject"
  ResourceObject:
    properties:
      id:
        description: "OSUUID of a person."
        type: string
      type:
        description: "Resource type: person"
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
      links:
        properties:
          self:
            type: string
          related:
            description: "Corresponding self link of person in Directory API"
            type: string
  Attributes:
    properties:
      username:
        description: "ONID of person"
        type: string
      firstName:
        type: string
      lastName:
        type: string
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
